extraction:
  cpp:
    prepare:
      packages:
      - libssl-dev
    configure:
      command:
      - "wget -q -O ptlib.zip https://github.com/willamowius/ptlib/archive/master.zip"
      - "unzip ptlib.zip"
      - "cd ptlib-master"
      - "export PTLIBDIR=$(pwd)"
      - "./configure --enable-ipv6 --disable-odbc --disable-sdl --disable-lua --disable-expat"
      - "make optnoshared"
      - "cd .."
      - "wget -q -O h323plus.zip https://github.com/willamowius/h323plus/archive/master.zip"
      - "unzip h323plus.zip"
      - "cd h323plus-master"
      - "export OPENH323DIR=$(pwd)"
      - "./configure --enable-h235 --enable-h46017 --enable-h46026 --enable-h46019m"
      - "VERBOSE=1 make optnoshared"
      - "cd .."
      - "VERBOSE=1 make optnoshared"

